---
services:
    web:
        # https://hub.docker.com/r/hhdev/php
        env_file: .env
        image: hhdev/php:5.6-apache-dev
        # image: hhdev/php:7.0-apache-dev
        # image: hhdev/php:7.1-apache-dev
        # image: hhdev/php:7.2-apache-dev
        # image: hhdev/php:7.3-apache-dev
        # image: hhdev/php:7.4-apache-dev
        # image: hhdev/php:8.0-apache-dev
        # image: hhdev/php:8.1-apache-dev
        # image: hhdev/php:8.2-apache-dev
        # image: hhdev/php:8.3-apache-dev
        # image: hhdev/php:8.4-apache-dev
        user: "${USER_ID}"
        network_mode: service:db
        volumes:
            - ./php.conf.d/additional.xdebug.ini:/usr/local/etc/php/conf.d/additional.xdebug.v2.ini
            - ./../:/var/www/html:rw

    db:
        # https://hub.docker.com/_/mariadb
        command:
          [
              "mysqld",
              "--character-set-server=utf8",
              "--collation-server=utf8_general_ci",
              "--max_allowed_packet=64M",
          ]
        env_file: .env
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_DATABASE: "${DB_DATABASE:-mariadb}"
            MYSQL_PASSWORD: "${DB_PASSWORD:-mariapass}"
            MYSQL_USER: "${DB_USER:-mariauser}"
        image: mysql:5.6         # used for TYPO3 6.x => 9.x
        # image: mariadb:10.4    # used for TYPO3 10.x => 13.x
        network_mode: service:selenium
        volumes:
            - storage_mysql:/var/lib/mysql
            # - storage_mariadb:/var/lib/mysql

    selenium:
        # https://hub.docker.com/r/selenium/standalone-chromium
        env_file: .env
        image: selenium/standalone-chromium:145.0
        ports:
            - "80${COMPOSE_PROJECT_PORT}:8080" # Apache httpd server
            - "79${COMPOSE_PROJECT_PORT}:7900" # Selenium server
        shm_size: 2gb

volumes:
    # storage_mariadb: ~
    storage_mysql: ~
